name    'arboeglin-coldfusion'
version '0.7.0'
source 'UNKNOWN'
author 'arboeglin'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

dependency 'ghoneycutt/common', '>= 0.2.0'
dependency 'ghoneycutt/java', '>= 0.0.1'
dependency 'puppetlabs/apache', '>= 0.5.0'
dependency 'puppetlabs/stdlib', '>= 3.2.x'
dependency 'maestrodev/wget', '>= 1.1.x'
dependency 'ghoneycutt/ssh', '>= 0.9.0'
